FROM dustynv/ros:noetic-pytorch-l4t-r35.2.1

# Remove OpenCV
RUN apt purge --yes '*opencv*'

# Install additional ROS packages
RUN apt update \
 && apt install --yes \
    ros-$ROS_DISTRO-ackermann-msgs \
    ros-$ROS_DISTRO-foxglove-msgs \
    ros-$ROS_DISTRO-vision-opencv \
    ros-$ROS_DISTRO-tf \
    ros-$ROS_DISTRO-tf2-ros

# Install Python packages
RUN apt update \
 && python3 -m pip install \
    pyrealsense2 \
    scikit-image

# Install Ultralytics
# See https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-jetson

# Downloads to user config dir
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/

# Install Linux packages
RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1 libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0

# Create working directory
WORKDIR /usr/src/ultralytics

# Clone Ultralytics repository
RUN git clone https://github.com/ultralytics/ultralytics -b main /usr/src/ultralytics

# Download model weights
ADD https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt /usr/src/ultralytics/

# Remove opencv-python from Ultralytics dependencies
# This command edits the pyproject.toml file to exclude opencv-python from the list of dependencies. 
RUN grep -v "opencv-python" pyproject.toml > temp.toml && mv temp.toml pyproject.toml

# Install pip packages
# The -e . at the end means "install the Python package located in the current directory from the toml file"
RUN python3 -m pip install --upgrade pip wheel \
    && pip install --no-cache tqdm matplotlib pyyaml psutil pandas onnx "numpy==1.23" \
    && pip install --no-cache -e .

# Set environment variables
ENV OMP_NUM_THREADS=1
